In [180]:
# Importing the required libraries
import numpy as np
import pandas as pd
import nltk
nltk.download('punkt') # one time execution
import re
import os
from sklearn.metrics.pairwise import cosine_similarity

[nltk_data] Downloading package punkt to /home/ubantu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [181]:
# Listing out the files and folder in the directories
os.listdir(os.getcwd())

['Text_summarizer.ipynb',
 'glove.6B.zip.5',
 'Untitled Folder',
 'Untitled1.ipynb',
 '.ipynb_checkpoints',
 'wget-log',
 'glove.6B.zip.2',
 'glove.6B.zip.5_FILES',
 'wget-log.1',
 'tennis_articles.csv',
 'glove.6B.100d.txt',
 'glove.6B.zip.4',
 'text_summ.py',
 'glove.6B.zip.3']

In [182]:
# Reading the csv file
df = pd.read_csv("tennis_articles.csv")

In [183]:
df.head()

article_id                                       article_text  \
0           1  Maria Sharapova has basically no friends as te...   
1           2  BASEL, Switzerland (AP), Roger Federer advance...   
2           3  Roger Federer has revealed that organisers of ...   
3           4  Kei Nishikori will try to end his long losing ...   
4           5  Federer, 37, first broke through on tour over ...   

                                              source  
0  https://www.tennisworldusa.org/tennis/news/Mar...  
1  http://www.tennis.com/pro-game/2018/10/copil-s...  
2  https://scroll.in/field/899938/tennis-roger-fe...  
3  http://www.tennis.com/pro-game/2018/10/nishiko...  
4  https://www.express.co.uk/sport/tennis/1036101...

In [184]:
# Parsing the sentences
from nltk.tokenize import sent_tokenize
sentences = []
for s in df['article_text']:
    sentences.append(sent_tokenize(s))

sentences = [y for x in sentences for y in x] # flatten list

In [185]:
sentences

['Maria Sharapova has basically no friends as tennis players on the WTA Tour.',
 "The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much.",
 'I think everyone knows this is my job here.',
 "When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.",
 "I'm a pretty competitive girl.",
 "I say my hellos, but I'm not sending any players flowers as well.",
 "Uhm, I'm not really friendly or close to many players.",
 "I have not a lot of friends away from the courts.'",
 'When she said she is not really close to a lot of players, is that something strategic that she is doing?',
 "Is it different on the men's tour than the women's tour?",
 "'No, not at all.

In [186]:
sentences[:5]

['Maria Sharapova has basically no friends as tennis players on the WTA Tour.',
 "The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much.",
 'I think everyone knows this is my job here.',
 "When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.",
 "I'm a pretty competitive girl."]

In [8]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove*.zip

--2019-07-24 10:23:37--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2019-07-24 10:23:38--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2019-07-24 10:23:40--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.5’

glove

In [194]:
# Extract word vectors
word_embeddings = {}
f = open('glove.6B.100d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    word_embeddings[word] = coefs
f.close()

In [195]:
len(word_embeddings)

400000

In [196]:
clear_sent = pd.Series(sentences).str.replace("[^a-zA-Z0-9]"," ")
clean_sentences = [s.lower() for s in clear_sent]

In [197]:
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /home/ubantu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [198]:
stp =stopwords.words("english")

In [199]:
def remove_stopwords(sent):
    new_sent= " ".join([i for i in sent if i not in stp])
    return(sent)

In [200]:
new_sent = [remove_stopwords(s) for s in clean_sentences]

In [55]:
sentence_vectors = []
for i in new_sent:
    if len(i) != 0:
        v = sum([word_embeddings.get(w, np.zeros((100,))) for w in i.split()])/(len(i.split())+0.001)
    else:
        v = np.zeros((100,))
    sentence_vectors.append(v)

In [57]:
len(sentence_vectors)

119

In [73]:
j="Shobhit is a good boy"
[word_embeddings.get(s,np.zeros((100,))) for s in j.split()]

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([-0.54264  ,  0.41476  ,  1.0322   , -0.40244  ,  0.46691  ,
         0.21816  , -0.074864 ,  0.47332  ,  0.080996 , -0.22079  ,
        -0.12808  , -0.1144   ,  0.50891  ,  0.11568  ,  0.028211 ,
        -0.3628   ,  0.43823  ,  0.047511 ,  0.20282  ,  0.49857  ,
        -0.10068  ,  0.13269  ,  0.16972  ,  0.11653  ,  0.31355  ,
         0.25713  ,  0.092783 , -0.56826  , -0.52975  , -0.051456 ,
        -0.67326  ,  0.92533  ,  0.2693   ,  0.22734  ,  0.66365  ,
         0.26221  ,  0.19719  ,  0.2609   ,  0.18774  , -0.3454   ,
      

In [75]:
j="Shobhit is a good boy"
sum([word_embeddings.get(s,np.zeros((100,))) for s in j.split()])

array([ 5.03410306e-02,  9.56275981e-01,  1.97169996e+00, -1.52669002e+00,
        8.89600217e-02,  1.77803998e+00,  5.48842005e-01,  7.77790010e-01,
       -9.33396984e-01, -6.11301512e-03, -1.42911004e+00, -2.08311933e-02,
        1.60568100e+00,  5.60664993e-01,  1.09964098e+00,  8.40080008e-02,
        1.35849801e+00, -9.40293018e-01, -1.04468003e-01,  2.55751602e+00,
        5.65164024e-01,  2.55936973e-01,  1.21079870e-02, -3.95310998e-01,
        1.54433998e+00,  1.36692998e+00, -2.00485704e+00, -2.41141996e+00,
       -9.45887998e-01,  1.19399398e+00, -1.42925996e+00,  2.88741994e+00,
        8.56828019e-01,  4.17410024e-01,  1.62350997e+00,  7.31500015e-01,
       -1.19503000e+00,  1.19081999e+00,  1.71701023e+00, -9.98480022e-01,
       -7.92494990e-01,  2.46851016e-01,  2.16115999e+00, -2.12561998e+00,
        1.85690030e-01, -5.38500249e-02,  6.42205983e-01, -2.98810005e-01,
       -1.96740985e-01, -2.71881799e+00, -6.39221996e-01, -1.90532996e+00,
        7.72370026e-01,  

In [76]:
# Similarity matrix
sim_matrix = np.zeros((119,119))

In [79]:
sim_matrix.shape

(119, 119)

In [84]:
for i in range(119):
    for j in range(119):
        if i != j:
            sim_matrix[i][j] = cosine_similarity(sentence_vectors[i].reshape(1,100), sentence_vectors[j].reshape(1,100))


In [83]:
sim_matrix

array([[0.        , 0.88726598, 0.83740002, ..., 0.89178896, 0.85290146,
        0.88390237],
       [0.88726598, 0.        , 0.92565334, ..., 0.9499433 , 0.93488741,
        0.96679443],
       [0.83740002, 0.92565334, 0.        , ..., 0.94383979, 0.87909085,
        0.90166336],
       ...,
       [0.89178896, 0.9499433 , 0.94383979, ..., 0.        , 0.9224717 ,
        0.96141666],
       [0.85290146, 0.93488741, 0.87909085, ..., 0.9224717 , 0.        ,
        0.93247139],
       [0.88390237, 0.96679443, 0.90166336, ..., 0.96141666, 0.93247139,
        0.        ]])

In [90]:
import networkx as nx

nx_graph = nx.from_numpy_array(sim_matrix)
scores = nx.pagerank(nx_graph)

In [91]:
scores

{0: 0.008347325221534776,
 1: 0.008526524885382775,
 2: 0.008051929532960153,
 3: 0.00873867212015731,
 4: 0.007863696511143181,
 5: 0.008351342831305302,
 6: 0.008378672423996574,
 7: 0.008558005846003948,
 8: 0.008518137122462858,
 9: 0.00847109690067102,
 10: 0.008393414917223781,
 11: 0.008525212898954778,
 12: 0.008078366284595764,
 13: 0.008398373296022277,
 14: 0.00839708659279284,
 15: 0.008529361673806114,
 16: 0.008302838778345187,
 17: 0.008001511065113938,
 18: 0.008417273863512192,
 19: 0.008543213735772572,
 20: 0.008554958449268932,
 21: 0.008327900956628798,
 22: 0.008131453441231116,
 23: 0.008518592266033298,
 24: 0.008400000877119985,
 25: 0.007635469031910654,
 26: 0.008320970003855864,
 27: 0.008493318553056798,
 28: 0.008592037625942751,
 29: 0.00865596523110366,
 30: 0.008732391041883765,
 31: 0.008553677197779497,
 32: 0.008339056323003077,
 33: 0.008458268407974597,
 34: 0.008620837111621104,
 35: 0.00857114116533974,
 36: 0.008142200387603415,
 37: 0.008541239

In [92]:
ranked_sentences = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)

In [94]:
# Starting on our own sentences

In [266]:
senr = df["article_text"][1]

In [267]:
sentt = sent_tokenize(senr)

In [260]:
sent = sent_tokenize(senr)

In [261]:
sent =pd.Series(sent).str.replace("[^A-Za-z0-9.-]"," ")

In [262]:
sent = sent[0]

In [205]:

sent = [s.lower() for s in sent]

In [206]:
sent

['basel  switzerland  ap   roger federer advanced to the 14th swiss indoors final of his career by beating seventh-seeded daniil medvedev 6-1  6-4 on saturday.',
 'seeking a ninth title at his hometown event  and a 99th overall  federer will play 93th-ranked marius copil on sunday.',
 'federer dominated the 20th-ranked medvedev and had his first match-point chance to break serve again at 5-1.',
 'he then dropped his serve to love  and let another match point slip in medvedev s next service game by netting a backhand.',
 'he clinched on his fourth chance when medvedev netted from the baseline.',
 'copil upset expectations of a federer final against alexander zverev in a 6-3  6-7  6   6-4 win over the fifth-ranked german in the earlier semifinal.',
 'the romanian aims for a first title after arriving at basel without a career win over a top-10 opponent.',
 'copil has two after also beating no.',
 '6 marin cilic in the second round.',
 'copil fired 26 aces past zverev and never dropped se

In [207]:
def remove_stp(se):
    new_sent=" ".join([i for i in se.split() if i not in stp])
    return(new_sent)

In [208]:
new_sent =[remove_stp(s) for s in sent]

In [209]:
new_sent

['basel switzerland ap roger federer advanced 14th swiss indoors final career beating seventh-seeded daniil medvedev 6-1 6-4 saturday.',
 'seeking ninth title hometown event 99th overall federer play 93th-ranked marius copil sunday.',
 'federer dominated 20th-ranked medvedev first match-point chance break serve 5-1.',
 'dropped serve love let another match point slip medvedev next service game netting backhand.',
 'clinched fourth chance medvedev netted baseline.',
 'copil upset expectations federer final alexander zverev 6-3 6-7 6 6-4 win fifth-ranked german earlier semifinal.',
 'romanian aims first title arriving basel without career win top-10 opponent.',
 'copil two also beating no.',
 '6 marin cilic second round.',
 'copil fired 26 aces past zverev never dropped serve clinching 2 1 2 hours forehand volley winner break zverev second time semifinal.',
 'came two rounds qualifying last weekend reach basel main draw including beating zverev older brother mischa.',
 'federer easier ti

In [214]:
sentence_vect=[]
for i in new_sent:
    if(len(i)!=0):
        v =sum([word_embeddings.get(w, np.zeros((100,))) for w in i.split()])/len(i.split())+0.001
    else:
        v= np.zeros((100,))
    sentence_vect.append(v)

In [221]:
simi_mat=np.zeros((12,12))

In [224]:
for i in range(12):
    for j in range(12):
        if(i!=j):
            simi_mat[i][j] = cosine_similarity(sentence_vect[i].reshape(1,100),sentence_vect[j].reshape(1,100))

In [ ]:
import networkx as nx

nx_graph = nx.from_numpy_array(sim_matrix)
scores = nx.pagerank(nx_graph)

In [231]:
import networkx as nx
nx_graph = nx.from_numpy_array(simi_mat)
scor =nx.pagerank(nx_graph)

In [250]:
scor

{0: 0.08158759184953603,
 1: 0.08381389285225274,
 2: 0.08691784029201734,
 3: 0.0842700658677753,
 4: 0.08087134998436062,
 5: 0.08138445672344073,
 6: 0.08405850418491362,
 7: 0.08465251656535268,
 8: 0.07360369254027656,
 9: 0.0870496956660244,
 10: 0.08522218036475583,
 11: 0.08656821310929409}

In [ ]:
sorted((senr[]))

In [268]:
ranked_sentences = sorted(((scor[i],s) for i,s in enumerate(sentt)), reverse=True)

In [271]:
for i in range(0,8):
    print(ranked_sentences[i][1])

Copil fired 26 aces past Zverev and never dropped serve, clinching after 2 1/2 hours with a forehand volley winner to break Zverev for the second time in the semifinal.
Federer dominated the 20th-ranked Medvedev and had his first match-point chance to break serve again at 5-1.
Federer had an easier time than in his only previous match against Medvedev, a three-setter at Shanghai two weeks ago.
He came through two rounds of qualifying last weekend to reach the Basel main draw, including beating Zverev's older brother, Mischa.
Copil has two after also beating No.
He then dropped his serve to love, and let another match point slip in Medvedev's next service game by netting a backhand.
The Romanian aims for a first title after arriving at Basel without a career win over a top-10 opponent.
Seeking a ninth title at his hometown event, and a 99th overall, Federer will play 93th-ranked Marius Copil on Sunday.
